project:
  type: website

website:
  title: "Colombian Fintech Customer Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project
        menu:
          - href: project/proposal.qmd
            text: Proposal
          - href: project/meeting_minutes.qmd
            text: Meeting Minutes
      - text: Modules
        menu:
          - href: modules/module_overview.qmd
            text: Customer Overview & Segmentation
          - href: modules/module_engagement.qmd
            text: Customer Engagement & Experience
          - href: modules/module_retention.qmd
            text: Retention Risk & Customer Value
      - href: poster.qmd
        text: Poster
      - href: user_guide.qmd
        text: User Guide
      - href: https://ligen.shinyapps.io/isss608_vaa_colombianfintech-project-shiny/
        text: Shiny App

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

author: "Group 7"